In [1]:
import numpy as np

In [2]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
a.shape

(24,)

In [4]:
a.size

24

In [8]:
b = a.reshape(4,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
#array[Chi so ma tran,Chi so dong,Chi so cot]
#array[star:stop:step,star:stop:step,star:stop:step]
b[1,:,1:]

array([[ 7,  8],
       [10, 11]])

In [12]:
# 6,8,9,11,18,20,21,23
b[1::2,:,::2]

array([[[ 6,  8],
        [ 9, 11]],

       [[18, 20],
        [21, 23]]])

In [13]:
b[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
b[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [16]:
b[1,1:,:]

array([[ 9, 10, 11]])

In [17]:
b[1,1,:]

array([ 9, 10, 11])

In [20]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [21]:
np.amax(b)

23

In [24]:
np.amax(b[1],1)

array([ 8, 11])

In [26]:
ind = np.where(b>17)
ind

(array([3, 3, 3, 3, 3, 3], dtype=int64),
 array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [27]:
b[ind]

array([18, 19, 20, 21, 22, 23])

In [28]:
b[b>17]

array([18, 19, 20, 21, 22, 23])

In [41]:
dt = np.dtype([('age','i8'),('name','U30')])
dt

dtype([('age', '<i8'), ('name', '<U30')])

In [42]:
name=['lan','an','trung']
age=[10,20,30]

In [43]:
emp = np.empty([len(name)],dtype=dt)

In [44]:
emp['name'] = name
emp['age'] = age

In [45]:
emp

array([(10, 'lan'), (20, 'an'), (30, 'trung')],
      dtype=[('age', '<i8'), ('name', '<U30')])

In [52]:
a = [1,2,3]
b = (4,5,6)
c = list(zip(a,b))
c

[(1, 4), (2, 5), (3, 6)]

In [54]:
for x in c:
    print(x[0],' - ', x[1])

1  -  4
2  -  5
3  -  6


In [55]:
for x,y in c:
    print(x,' - ', y)

1  -  4
2  -  5
3  -  6


In [58]:
emp = np.array(list(zip(age,name)),dtype=dt)
emp

array([(10, 'lan'), (20, 'an'), (30, 'trung')],
      dtype=[('age', '<i8'), ('name', '<U30')])

In [60]:
a = np.ones((3,3),dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [62]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
#2,0,1
a[[2,0,1],:]

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [64]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
a[:,[2,0,1]]

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [67]:
a = np.ones((3,3),dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
