## Chapter 3 - Exercise 1c: Thực hiện các yêu cầu sau, và đối chiếu với kết quả cho trước

In [2]:
import numpy as np

In [18]:
# Câu 1: Tạo array arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
arr_zeros = np.zeros((10,),dtype=np.int)
print ("arr_zeros:",arr_zeros)


arr_zeros: [0 0 0 0 0 0 0 0 0 0]


C:\Users\Abc\AppData\Local\Temp/ipykernel_4804/2743076336.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr_zeros = np.zeros((10,),dtype=np.int)


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
</pre>
  
</details>

In [19]:
# Câu 2: Tạo và in array arr_h có giá trị từ 10 đến 24 
arr_h = np.arange(10,24)
print("arr_h:",arr_h)

# In danh sách các phần tử theo tứ tự đảo ngược của arr_h vừa tạo


arr_h: [10 11 12 13 14 15 16 17 18 19 20 21 22 23]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
</pre>
  
</details>

In [20]:
# Câu 3: Cho array arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]) 
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]) 

# Tạo array arr_l từ arr_k với các phần tử khác 0
arr_l = arr_k[arr_k!=0]
print("Arr_l:",arr_l)

Arr_l: [1 2 8 2 1 3 5]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[1 2 0 8 2 0 1 3 0 5 0]
[1 2 8 2 1 3 5]
</pre>
  
</details>

In [21]:
# Câu 4: Từ array arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array
arr_l = np.append(arr_l,[10,20])
print("new arr_l:",arr_l)

new arr_l: [ 1  2  8  2  1  3  5 10 20]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[ 1  2  8  2  1  3  5 10 20]
</pre>
  
</details>

In [22]:
# Câu 5: Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5
arr_l = np.insert(arr_l,5,100)
print(arr_l)

[  1   2   8   2   1 100   3   5  10  20]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[  1   2   8   2   1 100   3   5  10  20]
</pre>
  
</details>

In [23]:
# Câu 6: Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2
lstIndex = [0,1,3]
arr_l = np.delete(arr_l,lstIndex)
print(arr_l)

[  8   1 100   3   5  10  20]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[  2   1 100   3   5  10  20]
</pre>
  
</details>